apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: reaction
spec:
  type: NodePort
  selector:
      app: reaction
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000
