name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    jobs:

  build:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        user: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number}}
      - name: Publish to Docker Git Hub
        uses: docker/build-push-action@v1
         with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: mynginx_image1/next
          tags: latest, ${{ github.run_number}}




      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
